#include "/home/admin-suz/Documents/Code/CGAL_TEST/CGAL-4.12.1/src/CGAL_Qt5/DemosMainWindow.cpp"
#include "/home/admin-suz/Documents/Code/CGAL_TEST/CGAL-4.12.1/src/CGAL_Qt5/GraphicsViewNavigation.cpp"
#include "/home/admin-suz/Documents/Code/CGAL_TEST/CGAL-4.12.1/src/CGAL_Qt5/GraphicsViewPolylineInput.cpp"
#include "/home/admin-suz/Documents/Code/CGAL_TEST/CGAL-4.12.1/src/CGAL_Qt5/debug.cpp"
#include "/home/admin-suz/Documents/Code/CGAL_TEST/CGAL-4.12.1/src/CGAL_Qt5/resources.cpp"
#include "/home/admin-suz/Documents/Code/CGAL_TEST/CGAL-4.12.1/src/CGAL_Qt5/utility.cpp"
